# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: busypy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='busypy.proto',
  package='busypy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x62usypy.proto\x12\x06\x62usypy\"c\n\x0e\x42usyPySettings\x12\x16\n\x0e\x63puLoadPercent\x18\x01 \x01(\x05\x12\x15\n\rmemoryPercent\x18\x02 \x01(\x05\x12\x12\n\nclientExit\x18\x03 \x01(\x08\x12\x0e\n\x06update\x18\x04 \x01(\x08\x32P\n\rBusyPyService\x12?\n\x0bGetSettings\x12\x16.busypy.BusyPySettings\x1a\x16.busypy.BusyPySettings\"\x00\x62\x06proto3')
)




_BUSYPYSETTINGS = _descriptor.Descriptor(
  name='BusyPySettings',
  full_name='busypy.BusyPySettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpuLoadPercent', full_name='busypy.BusyPySettings.cpuLoadPercent', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memoryPercent', full_name='busypy.BusyPySettings.memoryPercent', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientExit', full_name='busypy.BusyPySettings.clientExit', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update', full_name='busypy.BusyPySettings.update', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['BusyPySettings'] = _BUSYPYSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BusyPySettings = _reflection.GeneratedProtocolMessageType('BusyPySettings', (_message.Message,), dict(
  DESCRIPTOR = _BUSYPYSETTINGS,
  __module__ = 'busypy_pb2'
  # @@protoc_insertion_point(class_scope:busypy.BusyPySettings)
  ))
_sym_db.RegisterMessage(BusyPySettings)



_BUSYPYSERVICE = _descriptor.ServiceDescriptor(
  name='BusyPyService',
  full_name='busypy.BusyPyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=125,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSettings',
    full_name='busypy.BusyPyService.GetSettings',
    index=0,
    containing_service=None,
    input_type=_BUSYPYSETTINGS,
    output_type=_BUSYPYSETTINGS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUSYPYSERVICE)

DESCRIPTOR.services_by_name['BusyPyService'] = _BUSYPYSERVICE

# @@protoc_insertion_point(module_scope)
