# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import busypy_pb2 as busypy__pb2


class BusyPyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSettings = channel.unary_unary(
        '/busypy.BusyPyService/GetSettings',
        request_serializer=busypy__pb2.BusyPySettings.SerializeToString,
        response_deserializer=busypy__pb2.BusyPySettings.FromString,
        )


class BusyPyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSettings(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BusyPyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSettings': grpc.unary_unary_rpc_method_handler(
          servicer.GetSettings,
          request_deserializer=busypy__pb2.BusyPySettings.FromString,
          response_serializer=busypy__pb2.BusyPySettings.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'busypy.BusyPyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
